# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\meron\Documents\FISE28\Projet Info\IHM.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\meron\\Documents\\FISE28\\Projet Info\\../../../Pictures/Snooker.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Table = QtWidgets.QGraphicsView(self.centralwidget)
        self.Table.setGeometry(QtCore.QRect(30, 0, 400, 820))
        self.Table.setObjectName("Table")
        self.Angle = QtWidgets.QScrollBar(self.centralwidget)
        self.Angle.setGeometry(QtCore.QRect(460, 40, 171, 21))
        self.Angle.setMaximum(360)
        self.Angle.setProperty("value", 90)
        self.Angle.setOrientation(QtCore.Qt.Horizontal)
        self.Angle.setObjectName("Angle")
        self.Force = QtWidgets.QScrollBar(self.centralwidget)
        self.Force.setGeometry(QtCore.QRect(460, 100, 171, 21))
        self.Force.setMinimum(1)
        self.Force.setMaximum(100)
        self.Force.setProperty("value", 50)
        self.Force.setSliderPosition(50)
        self.Force.setOrientation(QtCore.Qt.Horizontal)
        self.Force.setObjectName("Force")
        self.label_angle = QtWidgets.QLabel(self.centralwidget)
        self.label_angle.setGeometry(QtCore.QRect(460, 19, 51, 21))
        self.label_angle.setObjectName("label_angle")
        self.label_force = QtWidgets.QLabel(self.centralwidget)
        self.label_force.setGeometry(QtCore.QRect(460, 90, 35, 10))
        self.label_force.setObjectName("label_force")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 150, 171, 21))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snooker"))
        self.label_angle.setText(_translate("MainWindow", "Angle (°)"))
        self.label_force.setText(_translate("MainWindow", "Force"))
        self.pushButton.setText(_translate("MainWindow", "TIRER !!"))
